<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vmlstar"
    nsURI="http://uk.ac.lancs.comp/vmlstar" nsPrefix="vmlstar">
  <eClassifiers xsi:type="ecore:EClass" name="VmlModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" eType="#//FeatureModelRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coreModel" eType="#//CoreModelRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concerns" upperBound="-1"
        eType="#//Concern" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureModelRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" derived="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fmURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreModelRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" derived="true"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coreURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concern">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subConcerns" upperBound="-1"
        eType="#//Concern" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variants" upperBound="-1"
        eType="#//Variant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pointcuts" upperBound="-1"
        eType="#//PointCut" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="onSelect" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onUnSelect" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ElementReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementReference" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedElements" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" changeable="false"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointCutReference" eSuperTypes="#//ElementReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pc" eType="#//PointCut"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointCut">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pce" eType="#//PointCutExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointCutExpression" abstract="true"
      eSuperTypes="#//ElementReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="PCEOperator" abstract="true" eSuperTypes="#//PointCutExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operands" upperBound="-1"
        eType="#//PointCutExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PCEAndOperator" eSuperTypes="#//PCEOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="PCEOrOperator" eSuperTypes="#//PCEOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="PCDesignator" abstract="true" eSuperTypes="#//PointCutExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
