<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vmlLangInst"
    nsURI="http://uk.ac.lancs.comp/vmlstar.lang_inst" nsPrefix="vmlstar.lang_inst">
  <eClassifiers xsi:type="ecore:EClass" name="LangInstModel">
    <eAnnotations source="comment">
      <details key="value" value="A model to describe a language extension for VML*"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fma" eType="#//FeatureModelAdapter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cma" eType="#//CoreModelAdapter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//ActionDescriptor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="designators" upperBound="-1"
        eType="#//DesignatorDescriptor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureModelAdapter">
    <eAnnotations source="comment">
      <details key="value" value="References an operation to use in determining the set of features for a given reference"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adapterClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="comment">
        <details key="value" value="Name of the class containing the operaton"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adapterOperation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="comment">
        <details key="value" value="Name of the operation. This operation must have the following signature:&#xD;&#xA;            Feature[*] getFeatures (String uri);"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreModelAdapter">
    <eAnnotations source="comment">
      <details key="value" value="References an operation to use in determining the set of model elements for a given reference"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adapterClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="comment">
        <details key="value" value="Name of the class containing the operaton"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adapterOperation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="comment">
        <details key="value" value="Name of the operation. This operation must have the following signature:&#xD;&#xA;            EObject[*] getModelElements (String uri);"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionDescriptor">
    <eAnnotations source="comment">
      <details key="value" value="Describes a custom action"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="comment">
        <details key="value" value="The name of the action. This will be used to invoke the action from a VML script."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numParams" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="comment">
        <details key="value" value="Number of parameters the action takes."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="evaluatorClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="comment">
        <details key="value" value="A class containing methods for executing the action and checking type-safety constraints."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="evaluatorMethod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="comment">
        <details key="value" value="Name of an operation implementing evaluation of the action. This must have the following signature:&#xD;&#xA;            void invoke (ElementReference[*] parameters)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkMethod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="comment">
        <details key="value" value="Name of an operation implementing type checking of the action's parameters. This must have the following signature:&#xD;&#xA;            boolean checkParameters (ElementReference[*] parameters)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DesignatorDescriptor">
    <eAnnotations source="comment">
      <details key="value" value="Describes a custom designator"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="comment">
        <details key="value" value="The name of the designator. This will be used to invoke the designator from a VML script."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numParams" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="comment">
        <details key="value" value="Number of parameters the designator takes."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="evaluatorClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="comment">
        <details key="value" value="A class containing methods for evaluating the designator and checking type-safety constraints."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="evaluatorMethod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="comment">
        <details key="value" value="Name of an operation implementing evaluation of the designator. This must have the following signature:&#xD;&#xA;            ElementReference[*] evaluate (CoreModelRef core, String[*] parameters)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkMethod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="comment">
        <details key="value" value="Name of an operation implementing type checking of the designator's parameters. This must have the following signature:&#xD;&#xA;            boolean checkParameters (CoreModelRef core, String[*] parameters)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
